/* ==========================================================================
   ACERVO ESTÁTICO DA SENEL
   --------------------------------------------------------------------------
   Este arquivo substitui o antigo banco MySQL. Todo o conteúdo abaixo foi
   consolidado a partir dos templates PHP, imagens e do dump mais recente
   (bdsenel_2022-04-20.sql).

   Para atualizar o site no futuro, basta editar estes objetos. O script.js
   lê os dados e monta automaticamente os blocos da página.
   ========================================================================== */

window.SENEL_DATA = {
  /* Linha do tempo que aparecia no antigo public/assets/js/timeline.js. */
  timeline: [
    { title: "SENEL 2018", date: "26 a 29 de março de 2018", note: "Retomada da Semana após um período sem edições." },
    { title: "Workshop 2018", date: "25 de outubro de 2018", note: "Continuidade das atividades no ano da retomada." },
    { title: "Visita técnica ao CEPEL", date: "12 de junho de 2019", note: "Aproximação entre estudantes, pesquisa e setor elétrico." },
    { title: "Visita técnica ao ONS", date: "13 de agosto de 2019", note: "Experiência sobre a operação do sistema elétrico brasileiro." },
    { title: "SENEL 2019", date: "19 a 23 de agosto de 2019", note: "A energia que moverá o Brasil." },
    { title: "SENEL Online", date: "26 de maio de 2020", note: "Novo formato de conteúdo durante a pandemia." },
    { title: "SENEL 2020", date: "23 a 27 de novembro de 2020", note: "Uma semana inteira de atividades remotas." },
    { title: "Visita virtual a Itaipu", date: "23 de junho de 2021", note: "Visita técnica virtual à Itaipu Binacional." },
    { title: "I Simpósio", date: "17 de agosto de 2021", note: "Mais um formato de encontro no calendário da equipe." },
    { title: "SENEL 2021", date: "22 a 26 de novembro de 2021", note: "Os Caminhos da Energia." },
  ],

  /* As edições aparecem da mais recente para a mais antiga. */
  editions: {
    "2021": {
      year: "2021",
      kicker: "Semana da Engenharia Elétrica",
      format: "Evento online",
      period: "22—26 nov. 2021",
      title: "SENEL 2021",
      theme: "Os Caminhos da Energia",
      banner: "assets/images/2021/capa/CAPA_2021_v2.jpg",
      bannerPosition: "center",
      description: [
        "De 22 a 26 de novembro aconteceu mais uma edição da Semana da Engenharia Elétrica da UFRJ.",
        "O evento foi inteiramente online e percorreu as etapas de geração, transmissão, distribuição e comercialização da energia, além de abordar o mercado de trabalho. As inscrições e os certificados foram administrados pela plataforma Even3.",
      ],
      aboutTheme: "A edição conectou as diferentes etapas que levam a energia da origem ao consumo, mostrando aos estudantes possibilidades técnicas e profissionais ao longo de toda essa jornada.",
      metrics: [
        { value: "05", label: "dias de evento" },
        { value: "09", label: "atividades registradas" },
        { value: "100%", label: "formato online" },
        { value: "04", label: "organizações parceiras" },
      ],
      tracks: [],
      schedule: [
        { date: "2021-11-22", time: "10:00", type: "Palestra", title: "Dimensionamento Fotovoltaico", speakers: "Alexandre Eustaquio Rosa", link: "https://youtu.be/ZEHPqyiF2DY" },
        { date: "2021-11-22", time: "18:30", type: "Palestra", title: "Integração do hidrogênio verde com as fontes solar e eólica", speakers: "Fernando Ribeiro de Melo Nunes", link: "https://youtu.be/M9kKig7oU_I" },
        { date: "2021-11-23", time: "09:00", type: "Minicurso e workshop", title: "ANAREDE", speakers: "Renan Pinto Fernandes", link: "https://youtu.be/8m5Ajj8XXmo" },
        { date: "2021-11-23", time: "18:00", type: "Palestra", title: "Sistemas Isolados no Brasil", speakers: "Michele Almeida de Souza", link: "https://youtu.be/eYNEHLfkcn0" },
        { date: "2021-11-24", time: "09:00", type: "Minicurso e workshop", title: "Data Science", speakers: "Rômulo Amaral", link: "https://youtu.be/HMdpzEZq6rY" },
        { date: "2021-11-24", time: "18:00", type: "Palestra", title: "A importância dos dados nas falhas de sistema", speakers: "RADIX", link: "https://youtu.be/rElHxN7EJ5E" },
        { date: "2021-11-25", time: "10:00", type: "Minicurso e workshop", title: "Metodologia SCRUM", speakers: "Palestrante não registrado", link: "https://youtu.be/wn2N8jA1ezE" },
        { date: "2021-11-25", time: "18:00", type: "Palestra", title: "Currículo e marketing pessoal", speakers: "Ricardo", link: "https://youtu.be/1h4ZJ0V5Tfk" },
        { date: "2021-11-26", time: "10:00", type: "Palestra", title: "Inovações elétricas no setor automobilístico", speakers: "Sidney Gonçalves", link: "https://youtu.be/yXikbbyQ_8A" },
      ],
      photos: [
        { src: "assets/images/2021/capa/CAPA_2021_v2.jpg", alt: "Arte de divulgação da SENEL 2021: Os Caminhos da Energia" },
        { src: "assets/images/2021/capa/CAPA_2021.jpg", alt: "Versão alternativa da arte da SENEL 2021" },
      ],
      sponsors: [
        { name: "Portal Solar", logo: "assets/images/2021/patrocinadores/portal_solar.png", category: "Ouro" },
        { name: "Radix", logo: "assets/images/2021/patrocinadores/radix.png", category: "Ouro" },
        { name: "RoboCore", logo: "assets/images/2021/patrocinadores/RC_yellow_site.png", category: "Prata" },
        { name: "Voitto", logo: "assets/images/2021/patrocinadores/Logo_Voitto.png", category: "Prata" },
      ],
    },

    "2020": {
      year: "2020",
      kicker: "Semana da Engenharia Elétrica",
      format: "Evento online",
      period: "23—27 nov. 2020",
      title: "SENEL 2020",
      theme: "Conhecimento e conexão em um novo formato",
      banner: "assets/images/2020/fotos/CAPA_2020.png",
      bannerPosition: "center",
      description: [
        "Em 2020, devido à pandemia, a SENEL adotou um novo modelo: a SENEL Online. O programa buscou manter os alunos ativos durante o período sem aulas presenciais.",
        "A partir de junho foram promovidas palestras periódicas no YouTube sobre temas técnicos, profissionais e sociais, incluindo uma mesa-redonda com ex-alunos. Em novembro, a SENEL 2020 reuniu palestras e minicursos durante uma semana.",
      ],
      aboutTheme: "A edição demonstrou a capacidade da equipe de adaptar o evento sem interromper a troca de conhecimento entre universidade, estudantes e profissionais.",
      metrics: [
        { value: "590", label: "inscritos na semana" },
        { value: "2.100", label: "visualizações" },
        { value: "176", label: "média de inscritos por evento" },
        { value: "612", label: "espectadores únicos" },
      ],
      tracks: [],
      schedule: [
        { date: "2020-11-23", time: "09:00", type: "Minicurso", title: "Wolfram Mathematica", speakers: "Daniel de Souza Carvalho" },
        { date: "2020-11-23", time: "18:00", type: "Palestra", title: "A Importância do Engenheiro Empreendedor", speakers: "Everton Pacheco Pereira de Moraes" },
        { date: "2020-11-24", time: "09:00", type: "Minicurso", title: "LaTeX", speakers: "Felipe Cabral" },
        { date: "2020-11-24", time: "18:00", type: "Palestra", title: "Novas tecnologias de Máquinas Elétricas", speakers: "Sebastião Lauro Nau" },
        { date: "2020-11-25", time: "18:00", type: "Palestra", title: "Energia Renovável do Oceano", speakers: "Segen Farid Estefen" },
        { date: "2020-11-26", time: "18:00", type: "Palestra", title: "Mercado de Energia", speakers: "Carlos Rogério Rocha" },
        { date: "2020-11-27", time: "09:00", type: "Minicurso", title: "PSCAD", speakers: "Elienai de Oliveira Macedo" },
      ],
      photos: [
        { src: "assets/images/2020/fotos/CAPA_2020.png", alt: "Arte da edição online da SENEL 2020" },
      ],
      sponsors: [],
    },

    "2019": {
      year: "2019",
      kicker: "Semana da Engenharia Elétrica",
      format: "Evento presencial",
      period: "19—23 ago. 2019",
      title: "SENEL 2019",
      theme: "A Energia que Moverá o Brasil",
      banner: "assets/images/2019/fotos/CAPA_2019.JPG",
      bannerPosition: "center",
      description: [
        "A Semana da Engenharia Elétrica da UFRJ é realizada no Centro de Tecnologia da Universidade Federal do Rio de Janeiro, com apoio do Departamento de Engenharia Elétrica.",
        "Em 2019, o evento aconteceu entre 19 e 23 de agosto e reuniu 25 atividades relacionadas ao tema “A Energia que Moverá o Brasil”.",
      ],
      aboutTheme: "O tema não se limitava às áreas técnicas que moveriam o setor elétrico. A edição destacou que a energia capaz de mover o Brasil também está nos estudantes de Engenharia e nos conhecimentos que o futuro engenheiro eletricista precisa dominar.",
      metrics: [
        { value: "55", label: "instituições impactadas" },
        { value: "1.022", label: "inscritos" },
        { value: "14", label: "palestras e mesas-redondas" },
        { value: "08", label: "árvores plantadas" },
      ],
      tracks: [
        { title: "Sistemas de Energia", description: "Quais são as novas tendências do sistema elétrico brasileiro?" },
        { title: "Perspectivas do Mercado de Trabalho", description: "O que espera o engenheiro eletricista à frente em sua carreira?" },
        { title: "Controle, Automação e Robótica", description: "A indústria 4.0 como protagonista do futuro da tecnologia." },
        { title: "Pesquisa, Desenvolvimento e Inovação", description: "O que há de novo na Engenharia?" },
        { title: "Sociedade e Sustentabilidade", description: "O desenvolvimento sustentável como chave para um bom crescimento." },
      ],
      schedule: [
        { date: "2019-08-19", time: "10:00", type: "Mesa-redonda", title: "A Energia que Moverá o Brasil", speakers: "Luiz Cosenza, Amaro e Edson Watanabe" },
        { date: "2019-08-19", time: "13:00", type: "Palestra", title: "O Profissional do Futuro", speakers: "Guilherme Monteiro" },
        { date: "2019-08-19", time: "13:00", type: "Minicurso", title: "Organon", speakers: "Paula Pereira" },
        { date: "2019-08-19", time: "15:00", type: "Mesa-redonda", title: "Impacto das Novas Fontes de Energia nas Redes de Distribuição", speakers: "David Parrini (PSR), Douglas Mota (ENEL), Bruno Sodré (Light) e Marcos Cesar Rocha (Light, mediador)" },
        { date: "2019-08-20", time: "08:00", type: "Minicurso", title: "Revit", speakers: "Fluxo Consultoria" },
        { date: "2019-08-20", time: "08:00", type: "Minicurso", title: "ANAREDE", speakers: "CEPEL" },
        { date: "2019-08-20", time: "13:00", type: "Palestra", title: "Inteligência Emocional", speakers: "Palestrante não registrado" },
        { date: "2019-08-20", time: "13:00", type: "Minicurso", title: "Robótica e Inteligência Artificial", speakers: "Palestrante não registrado" },
        { date: "2019-08-20", time: "13:00", type: "Palestra", title: "Desafios da Operação do Sistema Elétrico", speakers: "Palestrante não registrado" },
        { date: "2019-08-20", time: "15:00", type: "Palestra", title: "Internet das Coisas", speakers: "Representante IBM" },
        { date: "2019-08-21", time: "09:00", type: "Workshop", title: "Capacitação para atuar na área de energia solar", speakers: "Solarize Treinamentos" },
        { date: "2019-08-21", time: "13:00", type: "Minicurso", title: "VBA", speakers: "Hashtag Treinamentos" },
        { date: "2019-08-21", time: "13:00", type: "Palestra", title: "Utilização de Simuladores em Tempo Real para Microrredes", speakers: "Marcela Trindade (OPAL RT)" },
        { date: "2019-08-21", time: "15:00", type: "Palestra", title: "Inovação contra Furtos de Energia Elétrica", speakers: "Light" },
        { date: "2019-08-22", time: "08:00", type: "Minicurso", title: "Arduino", speakers: "Palestrante não registrado" },
        { date: "2019-08-22", time: "08:00", type: "Minicurso", title: "ANATEM", speakers: "CEPEL" },
        { date: "2019-08-22", time: "10:00", type: "Palestra", title: "Eficiência Energética", speakers: "Marcio Américo" },
        { date: "2019-08-22", time: "13:00", type: "Mesa-redonda", title: "Futuro dos Veículos Elétricos", speakers: "Palestrantes não registrados" },
        { date: "2019-08-22", time: "13:00", type: "Minicurso", title: "LaTeX", speakers: "A3 Consultoria" },
        { date: "2019-08-22", time: "15:00", type: "Mesa-redonda", title: "Energia e Sustentabilidade", speakers: "Palestrantes não registrados" },
        { date: "2019-08-23", time: "08:00", type: "Minicurso", title: "Power BI", speakers: "Hashtag Treinamentos" },
        { date: "2019-08-23", time: "10:00", type: "Palestra", title: "Arduino e Energia", speakers: "Mauro Sandro dos Reis e Júlio Cesar (CEFET/RJ)" },
        { date: "2019-08-23", time: "13:00", type: "Palestra", title: "Processo Seletivo e Comunicação de Alto Impacto", speakers: "Dan Godoy (IEG)" },
        { date: "2019-08-23", time: "15:00", type: "Palestra", title: "Encerramento: Grand Challenges for Engineering", speakers: "Nelson Martins" },
      ],
      photos: [
        { src: "assets/images/2019/fotos/CAPA_2019.JPG", alt: "Mesa-redonda A Energia que Moverá o Brasil" },
        { src: "assets/images/2019/fotos/Abertura.JPG", alt: "Abertura da SENEL 2019" },
        { src: "assets/images/2019/fotos/Aerodesign.JPG", alt: "Atividade de aerodesign na SENEL 2019" },
        { src: "assets/images/2019/fotos/BrindesPalestrantes.JPG", alt: "Brindes para palestrantes da SENEL 2019" },
        { src: "assets/images/2019/fotos/Coffebreak.JPG", alt: "Coffee break da SENEL 2019" },
        { src: "assets/images/2019/fotos/eRacing.JPG", alt: "Equipe e-Racing na SENEL 2019" },
        { src: "assets/images/2019/fotos/ELEPOT.JPG", alt: "Atividade da ELEPOT na SENEL 2019" },
        { src: "assets/images/2019/fotos/HallA.JPG", alt: "Hall do evento na SENEL 2019" },
        { src: "assets/images/2019/fotos/HallH.JPG", alt: "Exposição no hall da SENEL 2019" },
        { src: "assets/images/2019/fotos/Icarus.jpg", alt: "Projeto Icarus na SENEL 2019" },
        { src: "assets/images/2019/fotos/IMG_9922.JPG", alt: "Público da SENEL 2019" },
        { src: "assets/images/2019/fotos/InteligênciaEmocional.JPG", alt: "Palestra sobre inteligência emocional" },
        { src: "assets/images/2019/fotos/IoT.JPG", alt: "Palestra sobre Internet das Coisas" },
        { src: "assets/images/2019/fotos/LightHallA.JPG", alt: "Participação da Light no evento" },
        { src: "assets/images/2019/fotos/LightHallH.JPG", alt: "Estande da Light na SENEL 2019" },
        { src: "assets/images/2019/fotos/MesaVeículosElétricos.JPG", alt: "Mesa-redonda sobre veículos elétricos" },
        { src: "assets/images/2019/fotos/MinicursoANAREDE.JPG", alt: "Minicurso de ANAREDE" },
        { src: "assets/images/2019/fotos/MinicursoArduino.JPG", alt: "Minicurso de Arduino" },
        { src: "assets/images/2019/fotos/MinicursoIA.JPG", alt: "Minicurso de inteligência artificial" },
        { src: "assets/images/2019/fotos/Mudes.JPG", alt: "Atividade da Mudes na SENEL 2019" },
        { src: "assets/images/2019/fotos/RioLink.JPG", alt: "Participação da Rio Link" },
        { src: "assets/images/2019/fotos/SolarBrasil.jpg", alt: "Atividade sobre energia solar" },
        { src: "assets/images/2019/fotos/SorteioCREA.JPG", alt: "Sorteio em parceria com o CREA" },
        { src: "assets/images/2019/fotos/SorteioLivrosTAG.JPG", alt: "Sorteio de livros na SENEL 2019" },
        { src: "assets/images/2019/fotos/SorteioRobocore.JPG", alt: "Sorteio em parceria com a RoboCore" },
        { src: "assets/images/2019/fotos/WorkshopSolarize.JPG", alt: "Workshop da Solarize" },
      ],
      sponsors: [
        { name: "Yokogawa", logo: "assets/images/2019/patrocinadores/yokogawa.png", category: "Platina" },
        { name: "Rio Link", logo: "assets/images/2019/patrocinadores/riolink.png", category: "Platina" },
        { name: "Solarize", logo: "assets/images/2019/patrocinadores/solarize.png", category: "Ouro" },
        { name: "Manserv", logo: "assets/images/2019/patrocinadores/manserv.png", category: "Ouro" },
        { name: "Ohmini", logo: "assets/images/2019/patrocinadores/ohmini.png", category: "Ouro" },
        { name: "Light", logo: "assets/images/2019/patrocinadores/light.png", category: "Prata" },
        { name: "Radix", logo: "assets/images/2019/patrocinadores/radix.png", category: "Prata" },
        { name: "Alumni", logo: "assets/images/2019/patrocinadores/alumni.png", category: "Bronze" },
      ],
    },

    "2018": {
      year: "2018",
      kicker: "A retomada da Semana da Engenharia Elétrica",
      format: "Evento presencial",
      period: "26—29 mar. 2018",
      title: "SENEL 2018",
      theme: "Onde você se encaixa na Engenharia Elétrica?",
      banner: "assets/images/2018/fotos/CAPA-2018-1.JPG",
      bannerPosition: "center",
      description: [
        "A edição de 2018 marcou a retomada da Semana da Engenharia Elétrica da UFRJ após um período sem edições, no Centro de Tecnologia e com apoio do Departamento de Engenharia Elétrica.",
        "Entre 26 e 29 de março de 2018, a programação reuniu 21 atividades para discutir diferentes caminhos profissionais e áreas de atuação na Engenharia Elétrica.",
      ],
      aboutTheme: "“Onde você se encaixa na Engenharia Elétrica?” trouxe à tona os possíveis caminhos que um engenheiro eletricista pode seguir. As atividades chamaram atenção para áreas, competências e escolhas importantes para estudantes de todo o país.",
      metrics: [
        { value: "615", label: "inscritos" },
        { value: "11", label: "palestras e mesas-redondas" },
        { value: "21", label: "atividades no programa" },
        { value: "04", label: "dias de evento" },
      ],
      tracks: [],
      schedule: [
        { date: "2018-03-26", time: "10:00", type: "Mesa-redonda", title: "Futuro da Matriz Energética", speakers: "Palestrantes não registrados" },
        { date: "2018-03-26", time: "13:00", type: "Mesa-redonda", title: "Mulheres na Tecnologia", speakers: "Palestrantes não registrados" },
        { date: "2018-03-26", time: "13:00", type: "Minicurso", title: "Organon", speakers: "Leonardo e Paula Pereira (HPPA)" },
        { date: "2018-03-26", time: "15:00", type: "Palestra", title: "Energia Limpa", speakers: "Marcelo Arantes Severi (TGM) e Tarcisio Castro (PSR)" },
        { date: "2018-03-27", time: "09:00", type: "Workshop", title: "Energia Solar", speakers: "Alexandre Caseira (Vatio Energias Renováveis)" },
        { date: "2018-03-27", time: "10:00", type: "Palestra", title: "Tecnologia na Saúde", speakers: "Pablo Cevallos (Biomédica-COPPE) e Cláudio Marcus Boa Nova (Imprimindo Vida)" },
        { date: "2018-03-27", time: "13:00", type: "Workshop", title: "Compose / Activate / Embed", speakers: "Renato Tomaz (GT2 Tecnologia)" },
        { date: "2018-03-27", time: "13:00", type: "Workshop", title: "Malhas de Controle para simuladores full scope", speakers: "Alexandre Navarro (GT2 Tecnologia)" },
        { date: "2018-03-27", time: "13:00", type: "Workshop", title: "Conceitos de Energia Eólica", speakers: "Raphael Costa (EDF)" },
        { date: "2018-03-27", time: "15:00", type: "Palestra", title: "Mercado Financeiro da Energia Renovável", speakers: "Pedro Assumpção (EPP & PROSEEK)" },
        { date: "2018-03-27", time: "15:00", type: "Palestra", title: "Inovações no Setor Elétrico", speakers: "Maynara Aredes (PSR) e Flávio Martins (LASUP-UFRJ)" },
        { date: "2018-03-28", time: "09:00", type: "Minicurso", title: "Mathematica", speakers: "Miguel Quartin (IF-UFRJ)" },
        { date: "2018-03-28", time: "10:00", type: "Palestra", title: "Planejamento da Expansão da Geração e da Transmissão", speakers: "Ricardo Perez (PSR) e Thiago Dourado (EPE)" },
        { date: "2018-03-28", time: "10:00", type: "Palestra", title: "Impacto das Usinas", speakers: "Leandro Mota (Natural Energia)" },
        { date: "2018-03-28", time: "10:00", type: "Workshop", title: "Litros de Luz", speakers: "ONG Litros de Luz" },
        { date: "2018-03-28", time: "12:30", type: "Minicurso", title: "ANAREDE", speakers: "Renan Pinto Fernandes (CEPEL)" },
        { date: "2018-03-28", time: "13:00", type: "Palestra", title: "Controle Industrial", speakers: "Mário César Massa de Campos e Marcelo Gomes da Silva (Eletronuclear)" },
        { date: "2018-03-28", time: "13:00", type: "Workshop", title: "Empreendendo na Engenharia", speakers: "Marcos Martins (M11 Consultoria)" },
        { date: "2018-03-28", time: "13:00", type: "Workshop", title: "QC", speakers: "SKA" },
        { date: "2018-03-29", time: "09:00", type: "Minicurso", title: "VBA", speakers: "João Lira (Hashtag Treinamentos)" },
        { date: "2018-03-29", time: "10:00", type: "Mesa-redonda", title: "Futuro dos Transportes", speakers: "Ricardo Takahira (GFA Consulting Group), Edvaldo (LabH2) e Richard M. Stephan (LASUP-UFRJ)" },
        { date: "2018-03-29", time: "13:00", type: "Mesa-redonda", title: "Onde você se encaixa na Engenharia Elétrica?", speakers: "Ricardo Meliande (Ipiranga), Flávio Martins (LASUP-UFRJ) e Widson Braga" },
      ],
      photos: [
        { src: "assets/images/2018/fotos/CAPA-2018-1.JPG", alt: "Registro de capa da retomada da SENEL, em 2018" },
        { src: "assets/images/2018/fotos/2018-1.jpg", alt: "Atividade da SENEL 2018" },
        { src: "assets/images/2018/fotos/2018-2.JPG", alt: "Palestra da SENEL 2018" },
        { src: "assets/images/2018/fotos/2018-3.jpg", alt: "Público durante a SENEL 2018" },
        { src: "assets/images/2018/fotos/2018-4.JPG", alt: "Participantes da SENEL 2018" },
        { src: "assets/images/2018/fotos/2018-5.JPG", alt: "Atividade técnica da SENEL 2018" },
        { src: "assets/images/2018/fotos/2018-6.JPG", alt: "Equipe e participantes da SENEL 2018" },
        { src: "assets/images/2018/fotos/transporte_7.jpg", alt: "Atividade sobre o futuro dos transportes" },
      ],
      sponsors: [
        { name: "Manserv", logo: "assets/images/2018/patrocinadores/manserv.png", category: "Bronze" },
        { name: "Eletronuclear", logo: "assets/images/2018/patrocinadores/Eletronuclear.png", category: "Bronze" },
        { name: "GT2 Tecnologia", logo: "assets/images/2018/patrocinadores/GT2.png", category: "Bronze" },
        { name: "PSR", logo: "assets/images/2018/patrocinadores/PSR.png", category: "Bronze" },
      ],
    },
  },
};
